version: "3.8"

services:
  app:
    image: raspberrypi.local:5000/cow-home-games-ts:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - /var/lib/cow-home-games-ts:/var/lib/cow-home-games-ts
    restart: unless-stopped
